name: Update SUMMARY.md on PR

on:
  pull_request:
    branches:
      - staging
    types: [opened, synchronize, reopened]
    
permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure Git
        run: |
          git config user.name "devops-talus"
          git config user.email "devops@taluslabs.xyz"

      - name: Get list of added files
        id: added_files
        run: .github/scripts/get-added-files.sh ${{ github.event.pull_request.base.ref }}

      - name: Update SUMMARY.md
        run: .github/scripts/update-summary.sh

      - uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.DEVOPS_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.DEVOPS_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true
            
      - name: Commit and push changes (Signed)
        run: |
          git checkout ${{ github.event.pull_request.head.ref }}

          if git diff --exit-code SUMMARY.md; then
            echo "No changes to commit."
          else
            git add SUMMARY.md
            GIT_COMMITTER_DATE="$(date)" git commit -S -m "Update SUMMARY.md with new files under 'Looking for a home'" || exit 0
            git push origin ${{ github.event.pull_request.head.ref }}
          fi

      - name: Add TODO comment on PR
        if: env.new_entries != ''
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.payload.pull_request.number;
            const body = `⚠️ **TODO:** These new files need to be categorized properly in \`SUMMARY.md\`!  
            
            ## 📌 Newly Added Files:
            ${process.env.new_entries}

            👉 Please review and move them to the appropriate section.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: body
            });
